contributors/21700732.txt
=> 0423 homework -21700732-

contributors/21600567.txt
branch의 이름을  "newbranch"로 설정하고, 과제에 적힌대로 디렉토리 "contributors"에 텍스트 파일 "21600567.txt"을 작성하였습니다.
=> 21600567.txt added

contributors/21700351.txt
OSSLab_0423_3/contributors/ 에 21700351.txt 를 추가했습니다
- 해당 작업을 한 branch는 dachan이라는 branch내에서 작업을 했습니다
21700351.txt = "i agree to follow the Handong CSEE Standard honor code"입니다
=> Assignment_21700351_서다찬

contributors/21400126.txt
21400126 is added in Contributors file.
=> 21400126 added

contributors/21500602.txt
21500602 임연우입니다.
pull request 보냅니다!
=> 21500602.txt is added.

contributors/21900180.txt
=> 0423_H/W_21900180_Joo Young Kim

contributors/21600591
안녕하세요 교수님!
OSS 실습 03분반 2020.04.23 과제 Request 요청합니다!
- 21600591 임연수 -
=> add new textfile: 21600591

contributors/21600287.txt
안녕하세요 교수님! 16학번 박정현입니다.
New branch name: my_branch
File added: 21600287.txt
=> 21600287 created

contributors/21600090.txt
I added 21600090.txt in contributors folder.
=> Added 21600090.txt in contributors folder

contributors/21500362.txt
=> OSSLab 0423 21500362

contributors/21500798.txt
=> OSSLab 0423 21500798

contributors/21500474.txt
new branch name: b01
added file: 21500474.txt
by 21500474
=> 21500474 text added.

contributors/21400582.txt
new branch name: issue1
added file: 21400582.txt
=> 21400582 leejongwon

contributors/21700227.txt
I created 21700227.txt file that is written with "I agree to follow the Handong CSEE Standard honor code."
=> 21700227 file is created

contributors/21900160
=> 21900160 commit!

contributors/21900663.txt
Good morning, Professor.
May I request a pull request?
I made a branch named "Saehee" and created a text file name "21900663.txt" under the "contributors" folder. I also commited my changes on "Saehee".
Thank you.
I hope you have a great day, sir.
Saehee Jeong
=> Saehee added in the branch name Saehee.

contributors/21900786.txt
=> "21900786.txt added"

contributors/21800132.txt
출석확인용 과제입니다. 제 학번으로 된 txt파일에 요청하신 내용을 입력하였습니다.
=> Add contributor

contributors/21900516.txt
=> Add 21900516.txt in new branch

contributors/21600062, contributors/21600062.txt
I add one text file(21600062.txt) in 'contributors' folder.
=> OSS Assignment - pull request

contributors/21900658.txt
pull request가 안되어있어서 보냅니다 .. 죄송합니다!
=> 21900658.txt created

contributors/21800486.txt
branch name: tmp
contributors 에 21800486.txt를 추가했습니다.
=> homework 0423
